server:
  address: localhost
  port: 8080
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fch.buffetorder.entity
  configuration:
    map-underscore-to-camel-case: true

#数据库链接
spring:
  profiles:
    active: wx
  datasource:
    url: jdbc:mysql://localhost:3306/buffet_order?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123

  ## Redis 配置
  redis:
    ## Redis服务器地址
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:

    #配置rabbitMq 服务器
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #消息发送到交换机确认
    publisher-confirm-type: correlated
    #消息发送到队列确认
    publisher-returns: true
    #消费者数量
    listener:
      simple:
        #消费者数量
        concurrency: 1
        #最大消费者数量
        :max-concurrency: 10
        #消费者每次从队列获取的消息数量。写多了，如果长时间得不到消费，数据就一直得不到处理
        :prefetch: 1
        #消费接收确认机制-手动确认
        :acknowledge-mode: manual
  #文件
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

##redisson 配置
redisson:
  host:
    config: redis://localhost:6379

jwt:
  # 签名
  secret: BuffetOrder
  # 过期时间（ms）
  expire: 172800000
  # 剩余时间刷新（ms）
  expect: 86400000

url:
  upload-img: http://192.168.23.128:8080/file/upload

logging:
  level:
    com.fch.buffetorder.mapper.*: debug
